###
POST http://localhost:8080/api/banks
Content-Type: application/json

{
  "orgId": "org1",
  "legalName": "My Bank",
  "tin": "123456789",
  "lei": "123456789012345", 
  "routingNumber": "123456789",
  "phoneNumber": "1234567890",
  "email": "info@mybank.com"
}

###
GET http://localhost:8080/api/banks
Accept: application/json

###
@id =a216936d-2590-4ca0-b514-5945aae2704f
GET http://localhost:8080/api/banks/{{id}}
Accept: application/json

###
PUT http://localhost:8080/api/banks/{{id}}
Content-Type: application/json

{
    "orgId": "org2",
    "legalName": "Your Bank",
    "tin": "987654321",
    "lei": "98765432109876", 
    "routingNumber": "321654987",
    "phoneNumber": "3216549870",
    "email": "info@yourbank.com"
}

###
DELETE http://localhost:8080/api/banks/{{id}}