version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: banks
      POSTGRES_USER: banks
      POSTGRES_PASSWORD: s3cr3t
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    ports:
      - 5432:5432

volumes:
  db_data:

networks:
  db_network:
    driver: bridge